const exercises = [
  'Up and Down (12x)',
  'Arms-Under Arm Tightener',
  'Waist Bend Right',
  'Waist Bend Left',
  'Stretch-Head Tuck bt legs (20x)',
  'Stretch-Head Tuck R/L',
  'Neck-Rolls (10x)',
  'Neck-Side-to-Side (10x)',
  'Abs-Arms Up',
  'Abs-Right Leg Up',
  'Abs-Left Leg Up',
  'Abs-Arms and Legs Up',
  'Abs-Plank (60s)',
  'Abs-In and Out (20x)',
  'Legs-Up Back Down (10x)',
  'Legs-Up and Down',
  'Legs-Strech extended',
  'Legs-Posterior Press',
  'Pelvic Rotations Right (15x)',
  'Pelvic Rotations Left (15x)',
  'Pelvic Scoops (15x)',
  'Hips-Back Forth R',
  'Hips-Extended Up Down R',
  'Hips-Stand Out In R',
  'Hips-Stand Extended Up Down R',
  'Hips-Back Forth L',
  'Hips-Extended Up Down L',
  'Hips-Stand Out In L',
  'Hips-Stand Extended Up Down L',
  'Inner Thigh Squeeze',
  'Prone-Back & Leg Pulse',
  'Top Thigh Stretch',
  'Butter Fly Stretch',
];

export default exercises;